### PR TITLE
1、Added new spinner_popup_max_height attribute and property

### PR DESCRIPTION
**Pull request by wxw-9527**
Added new spinner_popup_max_height attribute and property

### CODE REVIEW

**Comment by skydoves** [comment]
Hey @wxw-9527, overall looks good to me :)
But before merging this, please run the command below:
```
./gradlew apiDump
```
Thank you!

**Comment by wxw-9527** [comment]
The reason for submitting is that I need to use this attribute in my project. Thank you.

**Comment by wxw-9527** [comment]
OK, I'm very sorry.

**Review by skydoves — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
