### PR TITLE
1、Make spinner_popup_background supports drawable files

### PR DESCRIPTION
**Pull request by wxw-9527**
## Guidelines
Make spinner_popup_background supports drawable files

### Types of changes
What types of changes does your code introduce?

- [ ] New feature (non-breaking change which adds functionality)

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```gradle
$ ./gradlew spotlessApply
```

Please correct any failures before requesting a review.

### CODE REVIEW

**Review by skydoves — COMMENTED** [review]
Hey @wxw-9527,
Overall looks good to me :)
But how do you think about supporting `spinner_popup_background_color` as well? We can support background color and drawable together and prioritize the background between them.

I think it would be much better if we could support the background color with the prioritization below:
1. background drawable
2. background color
3. nothing

Feel free to leave your thoughts about this, thank you!

**Comment by wxw-9527** [comment]
My English is not very good. I don't know if you understand what I think.
I think spinner_popup_background should support drawable and color like the background attribute of textview, not just color.

**Comment by wxw-9527** [comment]
Sorry, I forgot to say thank you.

**Comment by wxw-9527** [comment]
fixed #82

**Review by skydoves — APPROVED** [review]

**Pull request merged**
